FROM node:20-alpine as spia_build

ARG REACT_APP_LOCAL_IMAGE_PATH
ARG REACT_APP_API_URL
ARG REACT_APP_CLIENT_ID_GOOGLE
ARG REACT_APP_CLIENT_USER_INFO
ARG REACT_APP_IA

ENV REACT_APP_LOCAL_IMAGE_PATH $REACT_APP_LOCAL_IMAGE_PATH
ENV REACT_APP_API_URL $REACT_APP_API_URL
ENV REACT_APP_CLIENT_ID_GOOGLE $REACT_APP_CLIENT_ID_GOOGLE
ENV REACT_APP_CLIENT_USER_INFO $REACT_APP_CLIENT_USER_INFO
ENV REACT_APP_IA $REACT_APP_IA

WORKDIR /app

COPY package.json ./
RUN yarn install
COPY ./ ./

RUN yarn build


FROM nginx:stable-alpine

WORKDIR /var/www/html

COPY --from=spia_build /app/build/ ./

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
